RezzMeException: didn't have a __str__() method causing rather terse exceptions to be raised and caught.
also, we were not dealing correctly with a virgin hippo install:
grid_info.xml might not exist, in which case we need to find
default_grids.xml from hippo package directory. also, the path to
grid_info.xml on windows was completely wrong.


git-svn-id: http://forge.opensimulator.org/svn/rezzme/trunk@53 7bc2bfa8-0109-4806-b14c-dc71ee9d10d6